version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  # Add more services here as needed (e.g., database, cache, etc.)
